### ISSUE TITLE
datasets

### ISSUE THREAD

**Issue by Wenfengmi** [kieran514/robustdepth#5]
Can you directly send me the generated dataset? Thank you.

**Comment by kieran514** [comment]
Hello, thank you for your interest in our paper.

Due to the large size of the augmented dataset, we cannot directly share it. However, the dataset can still be created.

As an alternative, I have now provided the test data to demonstrate the file structure and allow for all evaluations without the need to generate the data.

**Comment by Wenfengmi** [comment]
Why can't I find the test dataset?

**Comment by kieran514** [comment]
This issue should be corrected now.
